development:
#  host: "http://test:test@127.0.0.1:8080/tunnel-web/secure/axis"
  host: "http://127.0.0.1:8080/tunnel-web/axis"

test:                    
  # qUqP5cyxm6YcTAhz05Hph5gvu9M=
  #host: "http://test:test@127.0.0.1:8080/tunnel-web/secure/axis"
  host: "http://127.0.0.1:8080/tunnel-web/axis"
    
production:
  host: "http://127.0.0.1:8080/tunnel-web/axis"
  